# Generated by Django 5.1.4 on 2024-12-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SnapForms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensereport",
            name="employee_id",
        ),
        migrations.RemoveField(
            model_name="expensereport",
            name="employee_name",
        ),
        migrations.RemoveField(
            model_name="expensereport",
            name="status",
        ),
        migrations.AddField(
            model_name="expensereport",
            name="employeeId",
            field=models.CharField(default="Testing", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expensereport",
            name="employeeName",
            field=models.CharField(default="Test", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expensereport",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="expensereport",
            name="contact",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="expensereport",
            name="currency",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="expensereport",
            name="department",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="expensereport",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
