# Generated by Django 5.1.4 on 2024-12-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SnapForms", "0002_remove_expensereport_employee_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensereport",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Approved"), ("D", "Denied")],
                default="P",
                max_length=1,
            ),
        ),
    ]
